DROP TABLE route_segments CASCADE CONSTRAINTS;
DROP TABLE routes CASCADE CONSTRAINTS;
DROP TABLE trucks CASCADE CONSTRAINTS;
DROP TABLE truck_details CASCADE CONSTRAINTS;
DROP TABLE cargo CASCADE CONSTRAINTS;
DROP TABLE waybills CASCADE CONSTRAINTS;
DROP TABLE orders CASCADE CONSTRAINTS;
DROP TABLE address CASCADE CONSTRAINTS;
DROP TABLE customers CASCADE CONSTRAINTS;


ALTER SESSION SET nls_date_format = 'DD/MON/YYYY hh24:mi:ss';
--stworzenie tabel g?ównych
CREATE TABLE customers (
    customer_id NUMBER generated by default on null as identity,
    customer_name VARCHAR2(200) NOT NULL,
    nip VARCHAR2(10) NOT NULL,
    address_id NUMBER,
    email VARCHAR2(50) NOT NULL,
    contact_number VARCHAR2(12) NOT NULL,
    CONSTRAINT customer_pk PRIMARY KEY(customer_id)
); 

CREATE TABLE address (
    address_id NUMBER generated by default on null as identity,
    house_number VARCHAR2(50),
    street VARCHAR2(50),
    post_code VARCHAR(10),
    city VARCHAR2(50),
    province VARCHAR2(50),
    country VARCHAR2(50),
    CONSTRAINT address_pk PRIMARY KEY(address_id)
);

CREATE TABLE orders (
    order_id NUMBER generated by default on null as identity,
    customer_id NUMBER NOT NULL,
    order_date DATE,
    order_status VARCHAR2(50),
    CONSTRAINT orders_pk PRIMARY KEY(order_id)
);


    
CREATE TABLE waybills (
    waybill_id NUMBER generated by default on null as identity,
    loading_point VARCHAR2(200),
    destination_point VARCHAR2(200),
    cargo_id NUMBER,
    issue_date DATE,
    CONSTRAINT waybill_pk PRIMARY KEY(waybill_id)
);

CREATE TABLE cargo (
    cargo_id NUMBER generated by default on null as identity,
    order_id NUMBER,
    registration_date DATE,
    description VARCHAR2(1000),
    Gross_weight_kg NUMBER,
    specific_instructions VARCHAR2(1000),
    status VARCHAR2(50),
    CONSTRAINT cargo_pk PRIMARY KEY(cargo_id)
);

CREATE TABLE trucks (
    truck_id NUMBER generated by default on null as identity,
    truck_model VARCHAR2(200),
    load_capacity NUMBER(10),
    truck_total NUMBER(10),
    truck_available NUMBER(10),
    CONSTRAINT truch_pk PRIMARY KEY(truck_id)
);

CREATE TABLE truck_details (
    truck_details_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    truck_id NUMBER,
    truck_status VARCHAR2(50),
    truck_number VARCHAR2(20) UNIQUE,
    insurance_number VARCHAR2(20) UNIQUE,
    availeble_capacity NUMBER(10),
    routes_executed NUMBER(20),
    km_total_driven NUMBER(20),
    CONSTRAINT truck_details_pk PRIMARY KEY(truck_details_id)
);

CREATE TABLE routes (
    route_id NUMBER generated by default on null as identity,
    route_date DATE,
    truck_details_id NUMBER,
    total_distance NUMBER(20),
    delivery_status VARCHAR2(50),
    CONSTRAINT routes_pk PRIMARY KEY(route_id)
);

CREATE TABLE route_segments (
    route_segment_id NUMBER generated by default on null as identity,
    route_id NUMBER,
    order_id NUMBER,
    start_location VARCHAR2(50),
    end_location VARCHAR2(50),
    segment_distance NUMBER(20),
    total_weight VARCHAR2(20),
    CONSTRAINT route_segment_pk PRIMARY KEY(route_segment_id)
);

--klucze obce CONSTRAINTS

--customers
ALTER TABLE customers ADD CONSTRAINT customers_address_fk 
    FOREIGN KEY(address_id) REFERENCES address(address_id);

--orders
ALTER TABLE orders ADD CONSTRAINT orders_customers_fk
    FOREIGN KEY(customer_id) REFERENCES customers(customer_id);


--waybills
ALTER TABLE waybills ADD CONSTRAINT waybill_cargo_fk
    FOREIGN KEY(cargo_id) REFERENCES cargo(cargo_id);
    
--cargo
ALTER TABLE cargo ADD CONSTRAINT cargo_orders_fk
    FOREIGN KEY(order_id) REFERENCES orders(order_id);
    
--routes
ALTER TABLE routes ADD CONSTRAINT routes_truck_details_fk
    FOREIGN KEY(truck_details_id) REFERENCES truck_details(truck_details_id);

--route_segments
ALTER TABLE route_segments ADD CONSTRAINT route_segments_routes_fk
    FOREIGN KEY(route_id) REFERENCES routes(route_id);
   

ALTER TABLE route_segments ADD CONSTRAINT route_segments_orders_fk
    FOREIGN KEY(order_id) REFERENCES orders(order_id);
    
--truck_details
ALTER TABLE truck_details ADD CONSTRAINT truck_details_fk
    FOREIGN KEY(truck_id) REFERENCES trucks(truck_id);


    

--check CONSTRAINTS
ALTER TABLE orders ADD CONSTRAINT orders_status_check CHECK ( order_status IN ('Przyjete', 'zaakceptowane', 'W trakcie', 'Wyslane', 'Anulowane', 'Zakonczone'));

ALTER TABLE cargo ADD CONSTRAINT cargo_check CHECK ( status IN ('Przyjete', 'Przydzielony', 'W drodze', 'Anulowane', 'Dostarczone'));

ALTER TABLE routes ADD CONSTRAINT delivery_status CHECK ( delivery_status IN ('Ladowanie', 'Gotowe do odprawy', 'W trakcie', 'Zakonczone', 'Anulowane'));

ALTER TABLE truck_details ADD CONSTRAINT truck_status_check CHECK ( truck_status IN ('dostepny', 'zajety'));

--Tworzenie indeksow

--orders idx
CREATE INDEX idx_orders_customer_id ON orders(customer_id);

--cargo idx
CREATE INDEX idx_cargo_order_id ON cargo(status, order_id);

CREATE UNIQUE INDEX idx_waybills_cargo_id ON waybills(cargo_id);

--routes idx
CREATE INDEX idx_routes_status_truck_details_id ON routes(truck_details_id, delivery_status);

--route_segments idx
CREATE INDEX idx_route_segments_route_id ON route_segments(route_id, order_id);

